version: '3.6'
services:

  maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v8-cli
    environment:
      DEBUG:
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      MAZE_BUGSNAG_API_KEY:
    ports:
      - "9000-9499:9339"
    volumes:
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-android-maze-runner}
