name: bugsnag_flutter
description: Bugsnag crash monitoring and reporting tool for Flutter apps
version: 0.0.1
homepage: https://www.bugsnag.com/

publish_to: 'none' # Remove this line once we're ready for release

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: "2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # This section identifies this Flutter project as a plugin project.
  #  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  #  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.bugsnag.flutter
        pluginClass: BugsnagFlutterPlugin
      ios:
        pluginClass: BugsnagFlutterPlugin
