agents:
  queue: macos-12-arm

steps:

  - label: ":test_tube: 3.10.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - make test

  - label: ":lint-roller: 3.10.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - make lint

  #
  # iOS
  #

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"

  - label: Build iOS Test Fixture 3.10.0

    timeout_in_minutes: 20
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    commands:
      - pod repo update trunk
      - features/scripts/build_ios_app.sh
    plugins:
      artifacts#v1.5.0:
        upload:
          from: "features/fixtures/app/build/ios/ipa/app.ipa"
          to: "features/fixtures/app/build/ios/ipa/app-3.10.0.ipa"
