agents:
  queue: opensource-arm-mac-cocoa-12

steps:

  - label: ":test_tube:"
    timeout_in_minutes: 10
    commands:
      - make test

  - label: Build iOS Test Fixture
    timeout_in_minutes: 20
    commands:
      - cd features/fixtures/app
      - flutter build ipa --export-options-plist=ios/exportOptions.plist
    plugins:
      artifacts#v1.5.0:
        upload: "features/fixtures/app/build/ios/ipa/app.ipa"

  - label: Build Android Test Fixture
    timeout_in_minutes: 20
    commands:
      - cd features/fixtures/app
      - flutter build apk
    plugins:
      artifacts#v1.5.0:
        upload: "features/fixtures/app/build/app/outputs/flutter-apk/app-release.apk"
