agents:
  queue: macos-12-arm

steps:

  - label: Build Example App 3.24.4
    timeout_in_minutes: 10
    agents:
      queue: macos-14-5
    env:
      FLUTTER_BIN: "/opt/flutter/3.24.4/bin/flutter"
    commands:
      - bundle install
      - pod repo update
      - make examples/flutter
      # Verify that App.framework's UUID (and therefore our `codeIdentifier`) changes when Dart code is touched
      - dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_before
      - sed -i '' -e 's/add_your_api_key_here/my_api_key/' examples/flutter/lib/main.dart
      - make examples/flutter
      - dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_after
      - test "$(cat uuid_before)" != "$(cat uuid_after)"
