agents:
  queue: "macos-15"

env:
  JAVA_VERSION: "17"
  XCODE_VERSION: "16.3.0"

steps:
  - group: "Unit Tests"
    steps:
      - label: ":test_tube: {{matrix}}"
        matrix:
          - "3.38.3"
          - "3.24.4"
          - "3.19.0"
          - "3.10.0"
        timeout_in_minutes: 10
        env:
          FLUTTER_VERSION: "{{matrix}}"
        commands:
          - "make test"

  - label: ":lint-roller: 3.38.3"
    timeout_in_minutes: 10
    env:
      FLUTTER_VERSION: "3.38.3"
    commands:
      - "make lint"

  - label: ":flutter: Build Example App 3.38.3"
    timeout_in_minutes: 10
    env:
      FLUTTER_VERSION: "3.38.3"
    commands:
      - "bundle install"
      - "pod repo update"
      - "make examples/flutter"
      # Verify that App.framework's UUID (and therefore our `codeIdentifier`) changes when Dart code is touched"
      - "dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_before"
      - "sed -i '' -e 's/add_your_api_key_here/my_api_key/' examples/flutter/lib/main.dart"
      - "make examples/flutter"
      - "dwarfdump --arch=arm64 --uuid examples/flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App | tee uuid_after"
      - "test \"$(cat uuid_before)\" != \"$(cat uuid_after)\""

  - group: " Build Test Fixtures"
    steps:
      - label: "Build iOS Test Fixture {{matrix}}"
        key: "ios-fixture"
        timeout_in_minutes: 20
        matrix:
          - "3.38.3"
          - "3.24.4"
          - "3.19.0"
          - "3.10.0"
        env:
          FLUTTER_VERSION: "{{matrix}}"
        commands:
          - "bundle install"
          - "pod repo update trunk"
          - "features/scripts/build_ios_app.sh"
        plugins:
          artifacts#v1.5.0:
            upload:
              from: "features/fixtures/app/build/ios/ipa/app.ipa"
              to: "features/fixtures/app/build/ios/ipa/app-{{matrix}}.ipa"

      - label: "Build Android Test Fixture {{matrix}}"
        key: "android-fixture"
        timeout_in_minutes: 20
        matrix:
#          - "3.38.3" Skipped: Waiting on PLAT-15326
          - "3.24.4"
          - "3.19.0"
          - "3.10.0"
        env:
          FLUTTER_VERSION: "{{matrix}}"
        commands:
          - "bundle install"
          - "features/scripts/build_android_app.sh"
        plugins:
          artifacts#v1.5.0:
            upload:
              from: "features/fixtures/app/build/app/outputs/flutter-apk/app-release.apk"
              to: "features/fixtures/app/build/app/outputs/flutter-apk/app-release-{{matrix}}.apk"

  - group: "End-to-end Tests"
    steps:
      - label: ":bitbar: Flutter {{matrix}} iOS end-to-end tests"
        depends_on: "ios-fixture"
        timeout_in_minutes: 20
        matrix:
          - "3.38.3"
          - "3.24.4"
          - "3.19.0"
          - "3.10.0"
        agents:
          queue: "opensource"
        plugins:
          artifacts#v1.5.0:
            download: "features/fixtures/app/build/ios/ipa/app-{{matrix}}.ipa"
            upload:
              - "maze_output/maze_output.zip"
              - "maze_output/failed/**/*"
          docker-compose#v4.7.0:
            pull: "maze-runner"
            run: "maze-runner"
            service-ports: true
            command:
              - "--app=/app/features/fixtures/app/build/ios/ipa/app-{{matrix}}.ipa"
              - "--farm=bb"
              - "--device=IOS_17|IOS_18|IOS_26"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2

      - label: ":browserstack: Flutter {{matrix}} Android 12 end-to-end tests"
        depends_on: "android-fixture"
        timeout_in_minutes: 20
        matrix:
#          - "3.38.3" Skipped: Waiting on PLAT-15326
          - "3.24.4"
          - "3.19.0"
          - "3.10.0"
        agents:
          queue: "opensource"
        plugins:
          artifacts#v1.5.0:
            download: "features/fixtures/app/build/app/outputs/flutter-apk/app-release-{{matrix}}.apk"
            upload:
              - "maze_output/maze_output.zip"
              - "maze_output/failed/**/*"
          docker-compose#v4.7.0:
            pull: "maze-runner"
            run: "maze-runner"
            service-ports: true
            command:
              - "--app=/app/features/fixtures/app/build/app/outputs/flutter-apk/app-release-{{matrix}}.apk"
              - "--farm=bs"
              - "--device=ANDROID_15"
              - "--appium-version=2.19.0"
              - "--fail-fast"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: "browserstack-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
