agents:
  queue: macos-12-arm

steps:

  - label: ":test_tube: 2.5.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/2.5.0/bin/flutter"
    commands:
      - make test

  - label: ":test_tube: 3.0.1"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.0.1/bin/flutter"
    commands:
      - make test

  - label: ":lint-roller: 2.5.0"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/2.5.0/bin/flutter"
    commands:
      - make lint

  - label: ":lint-roller: 3.0.1"
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/3.0.1/bin/flutter"
    commands:
      - make lint

  - label: Build Example App 2.5.0
    timeout_in_minutes: 10
    env:
      FLUTTER_BIN: "/opt/flutter/2.5.0/bin/flutter"
    commands:
      - pod repo update
      - make examples/flutter
      - zip -r FlutterExample.zip examples/flutter/
    plugins:
      artifacts#v1.5.0:
        upload: "FlutterExample.zip"
